apiVersion: v2
name: librenms
description: LibreNMS is an autodiscovering PHP/MySQL-based network monitoring system.
type: application
version: 9.2.1
appVersion: "26.8.1"
maintainers:
  - name: jacobw
    url: https://github.com/jacobw
dependencies:
  - name: redis
    version: "2.0.1"
    repository: "https://repo.helmforge.dev"
    condition: redis.enabled
  - name: mysql
    version: "~2.0.0"
    repository: "https://repo.helmforge.dev"
    condition: mysql.enabled
