{{- if not .Values.librenms.existingSecret }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace .Release.Name }}
{{- $appkey := "" }}
{{- if $secret }}
  {{- $appkey = index $secret.data "appkey" }}
{{- else if .Values.librenms.appkey }}
  {{- $appkey = .Values.librenms.appkey | b64enc }}
{{- else }}
  {{- $appkey = printf "base64:%s" (randAlphaNum 32) | b64enc }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
type: Opaque
data:
  appkey: {{ $appkey | quote }}
{{- end }}
