---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
data:
  TZ: {{ .Values.librenms.timezone}}
  DB_TIMEOUT: {{ include "librenms.dbTimeout" . | quote }}
  {{- $redis := include "librenms.redisEnabled" . }}
  {{- if $redis }}
  REDIS_HOST: {{ include "librenms.redisHost" . }}
  REDIS_PORT: {{ include "librenms.redisPort" . | quote }}
  REDIS_DB: {{ include "librenms.redisDb" . | quote }}
  {{- end }}
  {{- if .Values.librenms.rrdcached.enabled }}
  RRDCACHED_SERVER: "{{ .Release.Name }}-rrdcached:42217"
  {{- end }}
  {{- if $redis }}
  CACHE_DRIVER: redis
  SESSION_DRIVER: redis
  {{- else }}
  CACHE_DRIVER: file
  SESSION_DRIVER: file
  {{- end }}
  DB_HOST: {{ include "librenms.dbHost" . }}
  DB_PORT: {{ include "librenms.dbPort" . | quote }}
  DB_USERNAME: {{ include "librenms.dbUser" . }}
  DB_DATABASE: {{ include "librenms.dbName" . }}
  {{- with .Values.librenms.frontend.appUrl }}
  APP_URL: {{ . | quote }}
  {{- end }}
  {{- with .Values.librenms.frontend.appTrustedProxies }}
  APP_TRUSTED_PROXIES: {{ join "," . | quote }}
  {{- end }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-files
data:
  custom.php: |-
{{ tpl (.Files.Get "files/custom.php") . | indent 4 }}
  init.sh: |-
{{ .Files.Get "files/init.sh" | indent 4 }}
