{{- if .Values.librenms.snmptrapd.enabled }}
{{- $svc := .Values.librenms.snmptrapd.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-snmptrapd
  labels:
    {{- include "librenms.labels" (dict "root" . "component" "snmptrapd") | nindent 4 }}
  {{- with $svc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $svc.type }}
  {{- with $svc.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with $svc.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  selector:
    {{- include "librenms.selectorLabels" (dict "root" . "component" "snmptrapd") | nindent 4 }}
  ports:
    - name: snmptrap-udp
      protocol: UDP
      port: 162
      targetPort: 162
    - name: snmptrap-tcp
      protocol: TCP
      port: 162
      targetPort: 162
{{- end }}
