{{- if .Values.librenms.rrdcached.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rrdcached
  labels:
    {{- include "librenms.labels" (dict "root" . "component" "rrdcached") | nindent 4 }}
spec:
  selector:
    {{- include "librenms.selectorLabels" (dict "root" . "component" "rrdcached") | nindent 4 }}
  ports:
    - name: rrdcached
      protocol: TCP
      port: 42217
      targetPort: 42217
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rrdcached-headless
  labels:
    {{- include "librenms.labels" (dict "root" . "component" "rrdcached") | nindent 4 }}
spec:
  selector:
    {{- include "librenms.selectorLabels" (dict "root" . "component" "rrdcached") | nindent 4 }}
  ports:
    - name: rrdcached
      protocol: TCP
      port: 42217
      targetPort: 42217
  clusterIP: None
{{- end }}
