apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rrdcached
spec:
  selector:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: rrdcached
  ports:
    - name: rrdcached
      protocol: TCP
      port: 42217
      targetPort: 42217
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rrdcached-headless
spec:
  selector:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: rrdcached
  ports:
    - name: rrdcached
      protocol: TCP
      port: 42217
      targetPort: 42217
  clusterIP: None