name: Updste LibreNMS appVersion
on: 
  push:
    branches: 
      - renovate/*

jobs:
  set-appverions:
    runs-on: ubuntu-24.04

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

                    
      - name: Find image version
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.44.2/yq_linux_amd64.tar.gz -O /tmp/yq.tgz
          tar -xvf /tmp/yq.tgz --directory  /tmp
          chmod +x /tmp/yq_linux_amd64
          
          export VERSION=$(/tmp/yq_linux_amd64 '.librenms.image.tag' charts/librenms/values.yaml)
          echo "DETECTED VERSION $VERSION"
          /tmp/yq_linux_amd64 -e -i '.appVersion = env(VERSION)' charts/librenms/Chart.yaml

      
      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v6