name: Updste LibreNMS appVersion
on: 
  push:
    branches: 
      - renovate/*

jobs:
  set-appverions:
    runs-on: ubuntu-24.04

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

                    
      - name: Find image version
        uses: mikefarah/yq@v4.44.2
        run: |
          export VERSION=$(yq '.librenms.image.tag' charts/librenms/values.yaml)
          yq -e -i '.appVersion = $VERSION' charts/librenms/Chart.yaml

      
      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5